### ISSUE TITLE
文件夹推送方式会造成vps爆CPU 上传流量翻倍

### ISSUE THREAD

**Issue by djniche** [fuxin052/115_aria2#1]
我是VPS+fclone aria2自动上传的方式. 
通过网页发送到aria2以后.aria2文件也跟着上传了(其他推送没事)
造成了我vps爆CPU,流量也翻了几倍(已经把dir改成了我aria2的下载目录地址)
经测试 发送文件夹才会出现这问题. 
如果进到文件夹内全选发送不会出现

**Comment by fuxin052** [comment]
我不太了解fclone这个软件，
但是看起来属于fclone的配置问题
你应该增加规则让fclone排除.aria2文件

------

我这个脚本，如果选文件夹，那么下载下来的文件也会保持115里面的目录结构，我觉得这个功能是必要的，所以你只能去调整fclone那边

**Comment by djniche** [comment]
> 我不太了解fclone这个软件， 但是看起来属于fclone的配置问题 你应该增加规则让fclone排除.aria2文件
> 
> 我这个脚本，如果选文件夹，那么下载下来的文件也会保持115里面的目录结构，我觉得这个功能是必要的，所以你只能去调整fclone那边

我早就排除过了,其实就是rclone的改版 可以理解为rclone的修改版.我用pikpak推送也是保持了文件夹结构,下载正常.
但是这推送,会造成rclone move生成多个进程 我4任务下载完成后 可能会出现10+的rclone进程的move 跑上传 我也没搞懂,我甚至都屏蔽了10M以下的文件

**Comment by Celtillos** [comment]
应该就是fclone的问题，我之前有过这个问题改用rclone直接解决

**Comment by djniche** [comment]
> 

一会我试试Gclone gclone我记得也有bug 在某些情况下不会切换sa

**Comment by djniche** [comment]
> 应该就是fclone的问题，我之前有过这个问题改用rclone直接解决


一会我试试Gclone gclone我记得也有bug 在某些情况下不会切换sa

**Comment by Celtillos** [comment]
> > 应该就是fclone的问题，我之前有过这个问题改用rclone直接解决
> 
> 一会我试试Gclone gclone我记得也有bug 在某些情况下不会切换sa

大不了不用sa也没事，搬来搬去最后都是空
