### ISSUE TITLE
下载出错 HTTP 请求头错误或者无效

### ISSUE THREAD

**Issue by ww2283** [fuxin052/115_aria2#2]
请问'下载出错 HTTP 请求头错误或者无效.' 这种是什么情况呢？
之前有一个非常长的aria2的115下载队列，1200+。大概到第三天开始会偶尔出这种错误，后来就非常频繁了。从这以后似乎115导出到aria2的下载就都是这种错误了。导出过程本身是顺利的，只是不知道这种aria2的问题是为什么。 
用linux端的115客户端可以顺利下载（速度慢很多），所以不是115文件的问题。

个人猜测：115方面有某个时间段内的流量限制，可能是一周内不能超过某个值。上一次也遇到过，不过没有这次量大，所以我没有引起注意。如果是按照周来算的话， 这个值应该是在6TB左右。

用curl来测试的话，115方返回部分的信息是这样的：
{ [5 bytes data]
* Mark bundle as not supporting multiuse
< HTTP/1.1 403 Forbidden
< Server: AliyunOSS
< Date: Mon, 23 Jan 2023 20:21:16 GMT
< Content-Type: video/mp4
< Content-Length: 85
< Connection: keep-alive
< Content-Disposition: attachment
< Timing-Allow-Origin: *
< x-115-request-id: *********************************
<
{ [85 bytes data]
100    85  100    85    0     0     70      0  0:00:01  0:00:01 --:--:--    70
* Connection #0 to host cdnfhnfile.115.com left intact

**Comment by fuxin052** [comment]
1. 如果是流量超了，那么无解。
2. 导出出来很久还没开始下载，cookie可能会失效。这种问题可以将间隔时间调整长一点，让导出后不要等太长时间就开始下载。

**Comment by ww2283** [comment]
aria2的速度可能是因为比较快所以被针对了，现在用客户端是没问题的，只是客户端实在是一言难尽。我关这个话题了，留在closed里面给后来人一个reference吧。
PS：这个插件还是非常好用的👍

**Comment by gooddy2013** [comment]
我也同样问题。。。但是我肯定不是限流
