### ISSUE TITLE
最新版的115浏览器上使用不成功

### ISSUE THREAD

**Issue by aresvchou** [fuxin052/115_aria2#3]
25.0.6.5可以推送到docker，但是提示HTTP response header was bad or unexpected，请问要怎么设置一下？

**Comment by fuxin052** [comment]
没见过的错误, 可以提供更多信息吗?

**Comment by aresvchou** [comment]
我是在115流量器上装油猴然后安装你的脚本的，Aria2是群晖上docker安装的，我用雪月秋水的插件在360极速浏览器上登录115是可以正常推送下载的，但是脚本还是不行，不知道是哪里设置的问题。推送到Aria2后，里面出来任务，但是提示HTTP response header was bad or unexpected




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月20日(星期一) 晚上7:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [fuxin052/115_aria2] 最新版的115浏览器上使用不成功 (Issue #3)





 
没见过的错误, 可以提供更多信息吗?

**Comment by aresvchou** [comment]
> 没见过的错误, 可以提供更多信息吗?

我是在115浏览器上装油猴然后安装你的脚本的，Aria2是群晖上docker安装的，我用雪月秋水的插件在360极速浏览器上登录115是可以正常推送下载的，但是脚本还是不行，不知道是哪里设置的问题。推送到Aria2后，里面出来任务，但是提示HTTP response header was bad or unexpected
我怀疑是脚本这边是不是在新的浏览器上没有获取到115的cookies，提示的是header没有

**Comment by fuxin052** [comment]
你先推送一个下载任务, 暂停后看下这里有没有cookie
![image](https://user-images.githubusercontent.com/46592199/226328397-357c3cdd-e6eb-43bc-b8e5-0023bbce1651.png)

**Comment by aresvchou** [comment]
> 你先推送一个下载任务, 暂停后看下这里有没有cookie ![image](https://user-images.githubusercontent.com/46592199/226328397-357c3cdd-e6eb-43bc-b8e5-0023bbce1651.png)

![image](https://user-images.githubusercontent.com/96371079/226331709-1864075f-e87f-4e2d-a56c-88e4d0d3b6f1.png)
我的是这样的界面， 不太知道哪里可以看到那个信息

**Comment by aresvchou** [comment]
> > 你先推送一个下载任务, 暂停后看下这里有没有cookie ![image](https://user-images.githubusercontent.com/46592199/226328397-357c3cdd-e6eb-43bc-b8e5-0023bbce1651.png)
> 
> ![image](https://user-images.githubusercontent.com/96371079/226331709-1864075f-e87f-4e2d-a56c-88e4d0d3b6f1.png) 我的是这样的界面， 不太知道哪里可以看到那个信息

![image](https://user-images.githubusercontent.com/96371079/226333215-12852567-3f3b-48d0-b36b-aa9baef9e9fd.png)
出来个新问题，我用360极速浏览器登录的115，推送会下载一小段，然后又停了，又提示这个错误

**Comment by aresvchou** [comment]
> 你先推送一个下载任务, 暂停后看下这里有没有cookie ![image](https://user-images.githubusercontent.com/46592199/226328397-357c3cdd-e6eb-43bc-b8e5-0023bbce1651.png)

找到一部分问题了，会断了，是我还有其它下载，应该是超线程了，用360浏览器登录115后推送下载没问题。现在是115浏览器推送不了，是不是115浏览器有什么限制的？

**Comment by fuxin052** [comment]
我这个界面使用的ariang的 [https://github.com/mayswind/AriaNg](https://github.com/mayswind/AriaNg)  ,   你可以用这个提供的在线地址 [http://ariang.mayswind.net/latest](http://ariang.mayswind.net/latest) 可以看到 
多线程下载时, 原版aria2确实有概率会下载错误, 这种情况下点击继续下载是可以下载的, 
个人推荐用 [https://github.com/P3TERX/Aria2-Pro-Core](https://github.com/P3TERX/Aria2-Pro-Core) 提供的aria2程序, 修改了各种错误时能自动重试下载

**Comment by aresvchou** [comment]
> 我这个界面使用的ariang的 https://github.com/mayswind/AriaNg , 你可以用这个提供的在线地址 http://ariang.mayswind.net/latest 可以看到 多线程下载时, 原版aria2确实有概率会下载错误, 这种情况下点击继续下载是可以下载的, 个人推荐用 https://github.com/P3TERX/Aria2-Pro-Core 提供的aria2程序, 修改了各种错误时能自动重试下载

他的Aria2在docker里面好像没有webUI，我为了省事下的别的，下次再试试他的配合AriaNg吧

**Comment by fuxin052** [comment]
ui不一定非要部署在在一起, 使用浏览器扩展或者单独部署更灵活

**Comment by gooddy2013** [comment]
导入到aria2以后，提示HTTP返回头无效或无法识别，下载失败，请问大神有解吗？

**Comment by fuxin052** [comment]
个人建议使用chrome或者edge, 其他浏览器情况太多了
