### ISSUE TITLE
有文件导入到aria2失败，请检查设置

### ISSUE THREAD

**Issue by NotHFN** [fuxin052/115_aria2#5]
![image](https://github.com/fuxin052/115_aria2/assets/20512033/be764084-203f-420f-a31b-608ad0b5c790)
7万多文件只失败了一千左右，成功率还是很高的，这部分失败的原因是什么呢？

**Comment by fuxin052** [comment]
红色数字失败可能的原因
1. 115服务器上的文件是坏的,即使用115官方软件也无法下载, 这个可能性最大
2. aria2服务繁忙, 调用aria2接口时失败
